### ISSUE TITLE
Example usage/sample objects

### ISSUE THREAD

**Issue by instance-id** [OscarAbraham/UITKEditorAid#2]
Hey there,
    Looks like you have been doing some great work here. It would definitely be helpful to folks if there were a few samples of each one that could be seen in action. I checked through the documentation, while it is quite complete, I didn't see any actual example usage. I see that you have images of each one, do you happen to a scene with a few objects in it that you used in the images somewhere? It is always helpful to have a working copy to quickly check out to see if it would work as expected.

Here is one I threw together using a few scriptableobjects if anyone needs it. 

<details>
<summary>Lsit of Inspectors</summary>

```cs
// --------------------------
// --| MonoTest.cs ----------
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace instance.id
{
    [ExecuteInEditMode]
    public class MonoTest : MonoBehaviour
    {
        public List<TestSO> groupList = new List<TestSO>();

        private void OnEnable()
        {
            if (groupList.Count != 0) return;

            var gList = AssetDatabase.FindAssets($"t:{nameof(TestSO)}")
                .Select(guid => AssetDatabase.LoadAssetAtPath<TestSO>(AssetDatabase.GUIDToAssetPath(guid)))
                .ToList();

            if (gList.Count != 0) groupList = gList;
            else groupList.AddRange(new[]
            {
                ScriptableObject.CreateInstance<TestSO>(),
                ScriptableObject.CreateInstance<TestSO>(),
                ScriptableObject.CreateInstance<TestSO>()
            });

            for (int i = 0; i < groupList.Count; i++)
            {
                if (string.IsNullOrEmpty(groupList[i].name))  groupList[i].name = $"TestSO{i}";
            }
        }
    }
}
```

```cs
// --------------------------
// --| Place in Editor folder
// --| MonoTestEditor.cs ----
using ArteHacker.UITKEditorAid;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace instance.id.Editors
{
    [CustomEditor(typeof(MonoTest))]
    public class MonoTestEditor : Editor
    {
        private ListOfInspectors inspectorList;
        
        public override VisualElement CreateInspectorGUI()
        {
            var root = new VisualElement();
            var gList = serializedObject.FindProperty("groupList");
            inspectorList = new ListOfInspectors(gList);

            root.Add(inspectorList);
            root.Bind(serializedObject);
            root.Add(base.CreateInspectorGUI());
            return root;
        }
    }
}

```

```cs
using System.Collections.Generic;
using UnityEngine;

// --------------------------
// --| TestSO.cs ------------
namespace instance.id
{
    [CreateAssetMenu(menuName = "Test/TestObject", fileName = "TestObject.asset")]
    public class TestSO : ScriptableObject
    {
        public string someData;
        public float floatData;
        public List<Color> colorList = new List<Color>();

        private void OnEnable()
        {
            if (colorList.Count == 0)
                colorList.AddRange(new[]
                {
                    new Color(), new Color(), new Color()
                });
        }
    }
}

```

</details>

**Comment by OscarAbraham** [comment]
Hey! Thanks! Sorry, I hadn't seen this; maybe I need to reconfigure the alerts. I'm kind of new to managing open repos in Github. This will be a bit long, sorry for that; I don't have a enough time to measure my words right now.

There are some code examples for some basic stuff in the docs, but I completely agree that this is lacking proper samples, specially for complex stuff like _ListOfInspectors_. Managed references is another topic that could really benefit from samples. But ListOfInspector is really needs them, as there's nothing for it and its API is a bit ugly. I have no plans of cleaning its API, though. The samples could also help as a guide to UIToolkit's quirks in the editor. For example:

In your example, you don't need to do `root.Bind(serializedObject)` as the root is bound automatically bound by Unity. On the other hand, you should probably do `root.AddDelayed(inspectorList)` instead of `root.Add(inspectorList)`. _AddDelayed_ is an extension method that waits a frame to add an element. See, _ListOfInspectors_ has nested inspectors that are bound to their respective objects; if _TestSO_ contains a field with the same name as a field in _MonoTest_, that field's binding would be overriden by the roots binding. Nested Bindings can cause bugs that are hard to track, or even notice in time, when one doesn't expect them.

I was a reticent of doing much documentation for **ListOfInspectors**, because currently, the only good use case I know for it is to handle ScriptableObjects with subassets. The example for that requires a lot of asset handling stuff that doesn't have anything to do with UIToolkit, but it's doable. I should do it. I wouldn't use it with SOs and MBs, because SOs saved as part of a MB don't get cloned when copying the containing GameObject; also, SOs can't be saved in a prefab. It doesn't seem useful for Components or GameObjects, as there are already good ways to handle collections of those types.

Do you know any other use cases that you'd like to see an example for? Are there other things that you think could really use some samples? I'll prioritize this in my TODO list for open stuff. For now it looks like this:

1. Make some samples, at least for List of Inspectors.
2. Publish another repo or repos with some editor stuff that doesn't fit here, like support for generics and variant interfaces in Object fields with a picker, or a way to have custom names for individual components.
3. Give some maintenance to this package. We should try to use the USS variables that Unity made available in 2020, Editable labels have some problems in 2021, and there should be at least a mention that 2021.2 added support for _ListViews_ with elements of different heights. I should have added these in separate issues... Oh, well. Also, 2021.2 has a decent amount of bugs that affect this package, I should report them and/or do work arounds.
4. Add some nice to have stuff I already made to this package, like tabs, some extensions and some attributes.
5. Add more samples.

Also, Pull Requests are more than welcome. I'd just ask for a little patience because I don't have a lot of experience on this side of the PR process.

I might not have time to even get to step 1 until the weekend, maybe even until Monday. :/ Sorry for that. I'll leave this issue open until then. Thanks so much for pointing out this problem; I'd probably would have missed it because, in my mind, I understand my code.

**Comment by OscarAbraham** [comment]
An update: This will have to come later; some other priorities came up. But it will come.

**Comment by instance-id** [comment]
Hey, no worries. When I was playing around with things, I was able to get most of it figured out relatively easily, but I also tend to spend a decent amount of time experimenting with interesting and new (to me) concepts, so I am quite used to just diving into things.

I had been working on a dockable tool panel before that matched one of your mentioned uses cases pretty well, which was one of the reasons I wanted to take a peek at this in the first place. I had nested SO's in which I was displaying the child objects within the parent. I like "comparing notes", seeing how other people go about solving similar issues, etc. 

<details>
<summary>Action Panel</summary>

![](https://i.imgur.com/nPE9tAG.png)

</details>

That said, good catches on the code I posted, I wasn't thinking much of it at the time, I mostly just wanted to see it in action. As for USS variables, I didn't even realize that those were added. I am definitely going to have to take a look at those as well.

Anyways, seems like a really useful library, keep up the great work. :+1:

**Comment by OscarAbraham** [comment]
So I hadn't have time to do this until today, sorry. I've been trying to do an example that represents some realistic use case, to explain why some could need this, but I can't seem to come with a good one. The main point of this control is to emulate how components look on a GameObject, but I think it's not very self-evident why anyone would want to use it.

I am using it for an internal logic graph system, where nodes have a list of Action SO subassets that are hidden in the project view, so this control helps with that. And even for this kind of thing, I'd normally use POCOs with [SerializeReference](https://docs.unity3d.com/ScriptReference/SerializeReference.html) because they are much more easy to handle, but they have some bugs that get in the way for this particular case. The thing is, that kind of use is too complex for an example.

I wouldn't recommend this control for users that just want a convenient way to edit a referenced scriptable object without exiting the inspector, because it doesn't have a field to directly change scriptable object; I believe that right click -> Properties... solves that need very well, but if that is not enough, it'd be much better to use one of the many embedded inspector solutions for Unity.

I was thinking that maybe a goodish use case would be things that represent a specific set of assets, like an inventory where items are subassets. I'd normally avoid the pain of this and just select them from the project view, like multi-sprites, but I can see it being useful. Items could even have custom inspectors, to demonstrate other controls. One problem is that I intentionally avoided header dragging being useful to drop references to an SO, because it got in the way of my use case; it can be done, but it makes the example even more complex.

Also thing is that there are packages in GitHub that are actually made for handling sets of assets, I've never used them, but I recall seeing a couple that looked nice. So I feel even less inclined to recommend that list for that sort of thing.

And then I realized that it's been taking me a lot more time than it's worth, just to think about it. I have some updates to do to this plugin and I'll include an example for this when I upload them, but the example will probably be just a couple of scripts in the docs, with no realistic use case, and maybe a brief description of what I'm using it for. That is, unless a better idea comes up, but I don't expect it.

**Comment by OscarAbraham** [comment]
I've finally fixed the documentation site generation for this package. This means that the basic example for ListOfInspectors I made a while ago is visible here: https://artehacker.com/UITKEditorAid/api/ArteHacker.UITKEditorAid.ListOfInspectors.html.

As a side note, it's no longer needed to add this element with a delay. This is because ListOfInspectors now uses the new [BindingStopper ](https://artehacker.com/UITKEditorAid/api/ArteHacker.UITKEditorAid.BindingStopper.html) element internally to avoid issues when binding.
